### ISSUE TITLE
Error using node >14

### ISSUE THREAD

**Issue by tomplex** [faradayio/openapi-interfaces#21]
Using node 15:

```
$ node -v
v15.14.0
```

I got the following error:

```
$ npm run rest:generate

> sojourner@0.1.0 rest:generate
> openapi-interfaces ../../docs/sdk/static/api.interfaces.yml -o ../../docs/sdk/static/api.yml && openapi-interfaces --avoid-type-null ../../docs/sdk/static/api.interfaces.yml -o ../../docs/sdk/static/api.simplified.yml && openapi-typescript ../../docs/sdk/static/api.yml --output src/resources/rest_api/types.ts && ts-node generate-json-schema.ts

✨ openapi-typescript 4.3.0
🔭 Loading spec from file:///home/tom/dev/fdy/docs/sdk/static/api.yml…
TypeError: mime_1.default.getType is not a function
    at load (/home/tom/dev/fdy/src/sojourner/node_modules/openapi-typescript/dist/cjs/load.js:89:42)
    at async openapiTS (/home/tom/dev/fdy/src/sojourner/node_modules/openapi-typescript/dist/cjs/index.js:62:9)
    at async generateSchema (/home/tom/dev/fdy/src/sojourner/node_modules/openapi-typescript/bin/cli.js:106:18)
    at async /home/tom/dev/fdy/src/sojourner/node_modules/openapi-typescript/bin/cli.js:188:7
    at async Promise.all (index 0)
    at async main (/home/tom/dev/fdy/src/sojourner/node_modules/openapi-typescript/bin/cli.js:177:3)
```

I tried running `sudo npm install mime -g` as per a stackoverflow answer with no luck.

I installed node 14.9.2 (last 14.x version) and everything worked after that.

**Comment by emk** [comment]
@tomplex Thank you! I think I'll need more information here to figure this out.

- Do you believe that this is a bug in `openapi-interfaces` or in the third-party [`openapi-typescript`](https://www.npmjs.com/package/openapi-typescript)? I suspect this is an `openapi-typescript` bug, maybe?

But if you _do_ think this is an `openapi-interfaces` bug, then a few more questions. :-)

- Do you believe that `openapi-interfaces` is generating invalid OpenAPI 3.1 output?
    - If so, do you have a short example of the input and the output?
- Do you believe that `openapi-interfaces` is generating technically valid output that's still likely to break common OpenAPI 3.1 tools?
     - If so, what's the output, and what tools is it likely to break?

**Comment by tomplex** [comment]
hm, yes, I think you're right - this is probably an upstream issue. I can open something there and close this one.
