### ISSUE TITLE
Fix #MergePatch documentation

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#9]
Currently #MergePatch produces bad docs in readme. We can improve them by updating openapi-interfaces to do the following:
put the field description as a sibling to oneOf so it shows up in readme
first element:
title = "Overwrite"
description = "Set this value to overwrite the existing value"
second element:
title = "Nullify"
description = "Set this to `null` to nullify this field's existing value"

ex:
        attrition_cohort_id:
          description: "A cohort of counterexamples - people who have clearly failed to attain the outcome, as opposed to simply being indeterminate. This cohort is optional."
          oneOf:
            - type: string
              title: "Overwrite"
              description: "Set this value to overwrite the existing value"
              example: 3a6878ab-525f-418b-bea5-e9b8fd2dde2a
              format: uuid
            - type: "null"
              title: "Nullify"
              description: "Set this to `null` to nullify this field's existing value"

**Comment by hanakslr** [comment]
resolved in https://github.com/faradayio/openapi-interfaces/commit/d37adfd14e3a05ed3d7f030c76f1e94f2c65899e
